# Generated by Django 2.2.6 on 2019-11-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegeName', models.CharField(max_length=200)),
                ('collegeAddress', models.CharField(max_length=200)),
            ],
        ),
    ]
